let only_admin = "Only admin"
let number_out_of_bounds = "Number must be between 1 and 100"
let number_already_picked = "Number already picked"
let only_admin = "Only admin can check winner"
let number_not_picked = "Number not picked"